### PR TITLE
Minor style update

### PR DESCRIPTION
**Pull request by jesseflorig**
Minor style updates and housecleaning before My Cards overhaul.

-Added popover titles on various pages
-Added donator placeholder
-Moved twitter widget to footer

### CODE REVIEW

**Comment by ontehfritz** [comment]
:1 6x

**Comment by ontehfritz** [comment]
Hey, I noticed the search wasn't submitting ;)

**Comment by jesseflorig** [comment]
Search is broken? Shit!

I was using it to test the popovers. I dont know how I didn't catch it.

I'll take a look at it this afternoon when I add Joey to the about page.
—
Jesse

**Comment by ontehfritz** [comment]
No problem at all.

**Pull request merged**
